version: "3.3"

services:
  dashboard:
        build: .
        ports:
                - "5601:5601"
                - "9200:9200"
                - "5044:5044"
        volumes:
                - database:/var/lib/elasticsearch
                - ${PWD}/logs:/usr/home/logs
                - ${PWD}/dashboard:/usr/home/dashboard
        environment:
                - MAX_MAP_COUNT=262144
                - ES_CONNECT_RETRY=180
                - KIBANA_CONNECT_RETRY=180

volumes:
  database:
